spring.application.name=phegonbank

# server.port=8080

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/bank
spring.datasource.username=root
spring.datasource.password=numpy@123

# PostgreSQL Database Connection
# spring.datasource.url=jdbc:postgresql://localhost:5432/bank
# spring.datasource.username=postgres
# spring.datasource.password=root


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
